# Generated by Django 3.1.5 on 2021-01-24 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0004_jobapplication_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicant',
        ),
    ]
