# Generated by Django 3.1.5 on 2021-01-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0006_jobapplication_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('P', 'In Progress')], default='P', max_length=1),
        ),
    ]
