# Generated by Django 3.1.5 on 2021-01-23 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0003_auto_20210120_0033'),
        ('users', '0002_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffing.restaurant'),
        ),
    ]
